---
base: 'base'
local: 'local'
content: 'local/content'
specs: 'local/specs'
field_specs: 'local/specs/fields'
content_specs: 'local/specs/content'
group_specs: 'local/specs/groups'
views: 'local/views'
html_views: 'local/views/html'
html_snippets: 'local/views/html/snippets'
public: 'public'
...
